version: '3.9'

services:
  graphql:
    image: graphql
    build:
      context: ./graphql
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  discovery-service:
    image: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  listings-service:
    image: listings-service
    build:
      context: ./listings-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
      - "9199:9199"
    depends_on:
      - discovery-service

  payments-service:
    image: payments-service
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
      - "9195:9195"
    depends_on:
      - discovery-service

  booking-service:
    image: booking-service
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8380:8380"
      - "9093:9093"
    depends_on:
      - discovery-service
      - listings-service
      - payments-service

  dynamic-pricing-service:
    image: dynamic-pricing-service
    build:
      context: ./dynamic-pricing-service
      dockerfile: Dockerfile
    ports:
      - "8281:8281"
    depends_on:
      - discovery-service

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: rKxCJ1BP9IcXZETDwTq9gVbqb6pPy3cP
